spring:
  application:
    name: StuSelect
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db/stuselect.db 
    username: 
    password:
    hikari:
      connection-init-sql: "PRAGMA encoding = 'UTF-8';"
  sql:
    init:
      mode: never
      schema-locations: classpath:db/schema.sql
      
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.zfy.StuSelect.entity

jwt:
  secret: yourSecretKeyHereShouldBeLongEnoughForHS256Algorithm
  expiration: 86400 # 24小时有效期，以秒为单位